channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - bokeh=2.4.3
  - pandas=1.5.3
  - pip
  - pip:
      - -e .
      - requests==2.28.1
  - country_converter==1.0.0
  - pydeck==0.8.0
  - openai==0.27.2
  - numpy==1.24.2
  - geopandas==0.12.2
  - geopy==2.3.0
  - folium==0.14.0
  - regex==2022.7.9
  - ipython==8.10.0
  - shapely==2.0.1
